### ISSUE TITLE
Tags are not visible

### ISSUE THREAD

**Issue by Nenq** [raintank/memo#23]
Tags added via Slack messages are not visible on Grafana.

For example:

![Image](https://github.com/user-attachments/assets/2f0c5984-1b70-4bef-84fb-b60b2c7be61b)

Trace logs:

```
time="2025-06-12T10:43:21Z" level=debug msg="Received event: {Token:xyz TeamID:xyz Type:event_callback APIAppID:xyz EnterpriseID: Data:0xc0005960a0 InnerEvent:{Type:message Data:0xc000002140}}"

time="2025-06-12T10:43:21Z" level=debug msg="Inner event: &{ClientMsgID:xyz Type:message User:xyz Text:memo bug component:test ThreadTimeStamp: TimeStamp:1749725000.097279 Channel:xyz ChannelType:channel EventTimeStamp:1749725000.097279 UserTeam: SourceTeam: Message:<nil> PreviousMessage:<nil> Edited:<nil> SubType: BotID: Username: Icons:<nil> Upload:false Files:[] Attachments:[] Root:<nil>}"
```

Grafana database entry:

```
*************************** 1. row ***************************
          id: <redacted>
      org_id: 0
    alert_id: 0
     user_id: 0
dashboard_id: 0
    panel_id: 0
 category_id: NULL
        type:
       title:
        text: bug
      metric: NULL
  prev_state:
   new_state:
        data:
       epoch: 1749724976000
   region_id: 0
        tags: ["author:<redacted>","chan:<redacted>","memo","source:slack"]
     created: 1749725001611
     updated: 1749725001611
   epoch_end: 1749724976000
1 row in set (4.74 sec)
```
